### PR TITLE
Update example dependencies, recommend pyenv

### PR DESCRIPTION
**Pull request by lognaturel**
The intent for the app user provisioner example is for it to be a standalone script. I considered briefly whether it would make sense to introduce a pyproject.toml file for it but from https://stackoverflow.com/a/76548420/137744 decided requirements.txt was the most appropriate for pinned dependencies.

That led me to wonder a bit about the top-level pyproject.toml file and whether it should include pinned versions or not. I don't think it's a big deal because we don't know of anyone packaging pyodk as part of a larger system but we may want to eventually separate declared dependencies and pinned versions.

I also noticed that the readme mentions python 3.8 which it should not. @lindsay-stevens do you use `pyenv`? Happy to recommend something else if you prefer (but I do 💜 `pyenv`!).

### CODE REVIEW

**Comment by lindsay-stevens** [comment]
I think dependency pinning is more of a problem in regards to the way pyxform used to use `pip-tools` to specify the full dev installation environment, i.e. all dependencies-of-dependencies for packages that were installed. Doing that makes sense for an app and it's good use case for a separate file (similarly, [poetry ](https://python-poetry.org/) lock files), though it's the kind of thing that may hasten the descent into dependency hell for library users. Stating top-level dependencies with [version specifiers](https://pip.pypa.io/en/stable/reference/requirement-specifiers/) (e.g. an exact version, minimum, or a range) in `setup.py` / `setup.cfg` / `pyproject.toml` I think is OK, it's what is in place for pyodk and pyxform, and that's what many other popular library packages are doing as well, e.g. [django](https://github.com/django/django/blob/5f180216409d75290478c71ddb0ff8a68c91dc16/setup.cfg), [requests](https://github.com/psf/requests/blob/2a438c27b5a5828c8ea0dc958112eecffca70b12/setup.py), [boto3](https://github.com/boto/boto3/blob/2771ec793f88b60184404d786e7c7b026bee4dcc/setup.py), [pandas](https://github.com/pandas-dev/pandas/blob/main/pyproject.toml), [aiohttp](https://github.com/aio-libs/aiohttp/blob/master/setup.cfg). Having said that, I don't think it'll matter all that much if the example scripts keep using a `requirements.txt`. Another approach could be to declare the examples dependencies as optional dependency groups in the top-level `pyproject.toml`.

I recently tried pyenv for the first time, but only as a shortcut for the usual way I would compile a particular python version. It didn't really save that much time in the end, because I still had to install the system build dependencies specific to my distro of choice (Rocky), and then learn/remember how to invoke pyenv. I don't mind if you want to recommend pyenv, but it should go further down, e.g. in the "Develop" section because a) it's a tool that's more relevant to development, and b) to be recommending other packages so prominently (3rd paragraph from the top) reads like a non sequitur.

**Review by lindsay-stevens — APPROVED** [review]

**Comment by lognaturel** [comment]
> compile a particular python version

You... compile them?! Hardcore. 🤘

Does this mean that you only have a single version of Python on your system at once? Or do you use `python` binaries with a version built in like `python3.8` which was in the instructions before? Unfortunately the various projects I touch don't tend to all support the same Python versions at once. `pyenv` is crucial for me to be able to quickly switch between Python versions.

> it should go further down

What if it said "If you need to switch between multiple versions of Python, we recommend using `pyenv`?" I added that sentence in response to the `/usr/local/bin/python3.8 -m venv venv` that was in those opening instructions before. That looked like an attempt to juggle multiple python versions.

**Comment by lindsay-stevens** [comment]
`pyenv` is a bash application that automates a) compilation of python and b) switching between `python` defaults by modifying the PATH or other environment variables. The compiled pythons by default go in the home folder at `~/.pyenv/versions/`. To get a particular python venv going you can do `pyenv install 3.10.14; ~/.pyenv/versions/3.10.14/bin/python -m venv venv`.

Doing the same compilation without `pyenv` is only a few commands to download the tarball, configure the build, and run the makefile commands. One of the configs is to specify where to put the compiled python, and I was using `/usr/local/bin`. The major version is appended to the binary names. So that's how we get to `/usr/local/bin/python3.8` shown in the readme.

**Comment by lognaturel** [comment]
> compilation of python

🤔 That does make sense. It's so fast on my machine I guess I imagined it couldn't be compiled.

> To get a particular python venv going you can do pyenv install 3.10.14; ~/.pyenv/versions/3.10.14/bin/python -m venv venv

Right, but a more typical use of `pyenv` would be to do `pyenv global|local 3.10` and then use `python` directly. That feels like the biggest value-add to me.

**Comment by lognaturel** [comment]
@lindsay-stevens What do you think about framing this as "If you need to switch between multiple versions of Python, we recommend using pyenv" with the idea that it's a path to always calling `python` without explicit versioning. Or do you still prefer I move the recommendation down?

**Comment by lindsay-stevens** [comment]
Yeah I still think it's odd and also pyodk supports only one python version at a time. But lets move on to a brighter future!

**Comment by lognaturel** [comment]
Thanks for your flexibility! I'll keep thinking of a better framing. 🚀

**Pull request merged**
