### PR TITLE
Add client.app_users.create to create a new app user / assign forms

### LINKED ISSUE #7: Add client.app_users.create to create a new App User and optionally assign forms to it
## Use cases
It's common to want to bulk-configure App Users and currently the Central frontend does not make that easy. We also know some folks are getting user lists from external systems so it will always be something that is worth automating.

Sample script: https://gist.github.com/lognaturel/d538a40901aad8e5057bf0aeb8081ea6

## Proposed inputs
`display_names: List[str]` - list of display names for App Users to create

`forms: Optional[List[str]] = None` - list of form ids. If provided, the App Users are assigned each of the forms.
`project_id: Optional[int] = None`

## Proposed output
A list of objects representing the new App Users or at least the App User tokens. A common next step will be using the tokens to build QR codes. See below for a question about what to do when display name already exists.

### Where should this go?
Should we perhaps introduce `client.users` or `client.access` and put everything access-related in one place? We have to consider:
- App Users, project subresource
- Web Users, toplevel
- Public Access Links, form subresource

`client.access.create_app_users(["Foo"], ["bar", "baz"])` feels pretty good. But would users know to look for `access`?

Another option would be to put everything related to App Users in the project service since App Users are nested.

`client.projects.create_app_users` seems it could be more intuitive.

### Should it be responsible for verifying whether there's a `displayName` match?
Currently `displayName` is not required by Central to be unique. In practice, it's probably always desirable that it is because they're being treated as usernames. My current thinking is that the most useful thing to do is to make this method a "get or create". First fetch the full list of app users, see if there are matches, and only create App Users with new display names. This is what the sample script above does. If we do it that way, I think we should include the existing App Users in the array that's returned.

### PR DESCRIPTION
**Pull request by lindsay-stevens**
Closes #7

- add project.create_app_users
  - roles.py to lookup roles by name.
  - project_app_users.py to list and create project app users.
  - form_assignments.py to assign user/role/form.
- forms.py: fix type annotation to allow any iterable since no indexing needed, just iteration. e.g. allow generators.
- test_forms.py: fix call_count test, which should check the count rather than set it.

#### What has been done to verify that this works as intended?

Mock-based tests for the main use cases of project.create_app_users, as well as for Roles and ProjectAppUsers. Not for FormAssignment since the `assign()` method only returns a `success` bool. Also integration tests in test_client.py,

#### Why is this the best possible solution? Were any other approaches considered?

Follows the ticket specification and use case shown in the linked gist. I wondered if allowing assignment for existing users would be useful, e.g. a new form is added - but then the method is called "create" not update.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

New feature. One minor change to the type annotation on `client.forms.update` arg `attachments` to allow an `Iterable` since `Sequence` unnecessarily excludes generators.

#### Do we need any specific form for testing your changes? If so, please attach one.

The integration tests in `test_client.py` assume the project has forms named `range` and `pull_data` but these are in the repo.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.

The README is updated to list the new public method.

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests`
- [x] run `nosetests` and verified all tests pass
- [x] run `python bin/pre_commit.py` to format / lint code
- [x] verified that any code or assets from external sources are properly credited in comments

### CODE REVIEW

**Comment by lindsay-stevens** [comment]
One deviation from the example gist is the role lookup. In the gist, the `app_user_role_id` is known to be `2`, but I assume users may not know this. Or maybe they do know it, and the lookup is a waste? Or maybe the role can never be anything but "app user" (`2`) - seeing as the new method is about app_users? The apiary docs seemed a bit open ended about which roles can be accepted. If it's always role_id=2 then let me know and I can revise accordingly.

**Comment by lindsay-stevens** [comment]
@lognaturel reminder for this PR ready for review

**Comment by lognaturel** [comment]
Apologies for the crickets. I see this, a first pass looks good, but I actually want to try it and haven’t had time yet. 😩

**Comment by lognaturel** [comment]
> maybe the role can never be anything but "app user" (2) - seeing as the new method is about app_users

I hadn't completely absorbed the role aspect of things in my first pass through. This is correct -- the role should always be 2. From a Central user's perspective, App Users are a specific kind of user. It's a system implementation detail that in fact Central represents different access types (App Users, the various Web User roles, Public Links) as actor roles. In this case the high-level need is specifically around App Users. I think we may also want to introduce a method to provision Web Users but that would be at the top level and I haven't heard of a need for it yet.

Other than that, tests and behavior look good!

**Comment by lindsay-stevens** [comment]
@lognaturel thanks for clarifying, I removed the role param / lookup and changed the form assignment to use "2" for the role_id.

**Review by lognaturel — APPROVED** [review]
Woohoo, App Users for everyone! 🎉

**Pull request merged**
