### PR TITLE
Introduce mkdocs for API documentation

### PR DESCRIPTION
**Pull request by lognaturel**
It's helpful to have reference for available functionality in a nicely-rendered way.

Remaining to do:
- Update action to publish to github pages
- Update Github config for github pages
- Add link to published docs to readme

#### What has been done to verify that this works as intended?

`mkdocs serve`, looked at the resulting docs.

#### Why is this the best possible solution? Were any other approaches considered?
My goals for this were:
- reuse the README. It's helpful to have a single source of truth for landing content
- use markdown. ODK docs use sphinx which has a lot of nice properties but RST is painful
- autogenerate docs from existing docstrings
- provide direct links to each method part of our public API
- get something minimal up that we can start iterating on

Overall, I'm really happy with `mkdocs` and `mkdocstrings`. This was straightforward to put together and I think it looks nice. Unfortunately, it doesn't fit in with the styling of any of our existing docs. I think we can deal with that separately.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

No change to code.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
This is the change to documentation.

#### Before submitting this PR, please make sure you have:
- [x] included test cases for core behavior and edge cases in `tests`
- [x] run `nosetests` and verified all tests pass
- [x] run `python bin/pre_commit.py` to format / lint code
- [x] verified that any code or assets from external sources are properly credited in comments

### CODE REVIEW

**Comment by lognaturel** [comment]
I'd be interested in your high-level thoughts @lindsay-stevens. I believe this will make the library a lot more accessible so I'm eager to get it in. If you have some cycles and can take on the couple of todos at the top that would also be wonderful.

Something else I think we should add are recommendations for error handling. I believe all error states result in exceptions and most provide the raw error message from Central. It would be helpful to document that and I think the info on logging that's in the readme now could be moved to that section as well. I think you're best positioned to write a bit about that.

**Comment by lognaturel** [comment]
> can take on the couple of todos at the top that would also be wonderful

But your high-level feedback is the most important thing and I can take those todos!

**Comment by lindsay-stevens** [comment]
Hi @lognaturel looks good! I haven't used mkdocs so it took a little bit of digging in the docs to get up to speed. I opened [a PR](https://github.com/lognaturel/pyodk/pull/1) in your fork with some suggestions.

About the todo items, I don't have privileges to enable Pages on this repo. But it looks like there's a script [`mkdocs gh-deploy`](https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages) to take care of publishing. About the actions workflow, it's possible to set a trigger only for edits on certain paths:

```yaml
on:
  push:
    paths:
      - docs
      - README.md
```

**Comment by lognaturel** [comment]
Thank you! Hoping I can come back to it near the end of the week.

**Comment by lognaturel** [comment]
@yanokwa has requested that I explore doing these docs within https://github.com/getodk/docs so we have more overall consistency.

**Comment by lognaturel** [comment]
I don’t see a great short-term path to a more integrated docs experience. I’ve discussed with @yanokwa and we’re going to start with this so there’s at least some easy-to-use documentation. We can iterate and redirect as needed.

**Comment by lognaturel** [comment]
I had to remove `pywin32==305` to install on my Mac.

**Review by yanokwa — APPROVED** [review]
LGTM

**Pull request merged**
